#+BEGIN_COMMENT
.. title: Projects
.. slug: projects
.. date: 2023-07-03 15:13:21 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT


These are a list of pretty-much completed projects, or things I've deemed worthy of this page. The projects are ordered by when they were considered "done".

* Fishy Merry-Go-Round
An interactive art exhibit. Hand-coloured fish are scanned and displayed in an animated coral reef. Here's what it looks like:

#+BEGIN_EXPORT html
<br>
<video controls>
  <source src="/assets/recording.mp4" type="video/mp4" />
</video>
</br>
#+END_EXPORT

Yes, it's kinda choppy, probably because it was done on a Thinkpad T480 with an Intel UHD620. It's smoother in real life. 
It was displayed at MakerFaire Hyderabad 2023, and had quite a few visitors (around 700 total fish over the 2 days)! The recording above is of the improved version, in which I squashed some (software) bugs and added better visuals (caustics and the volumetric effect).

Source code: https://github.com/ru2saig/fishy-merry-go-round. 

* Unlauncher Fork
This is my fork of [[https://jkuester.github.io/unlauncher/][jkuester's Unlauncher]]. I've added a few quality of life improvements, such as wallpapers, double-tap to sleep and a long press menu as well. You use your phone, not the other way around!

Source code: https://github.com/ru2saig/unlauncher.
 
 
* xfce4-kind-plugin
This is a panel-plugin I made for the [[https://xfce.org/][XFCE4 project]]. It displays the status of the keyboard indicators in the panel. Pretty nifty. The main purpose was to learn how plugins are made, and get some experience with the C programming language, autotools and XFCE4 panel plugins.

Source code: https://github.com/ru2saig/xfce4-kind-plugin
 
 
* BTTerminal
An bluetooth terminal written in Java for Android in order to send commands to a HC-05 bluetooth module. 

Source code: https://gitlab.com/ru2saig/BTTerminal
 
 
* MatrixUI
This app controls a simple 3x3 daisy-chained LED matrix, driven by and Arduino. The app communicates with the circuit over bluetooth, with a HC-05. 

Source code: https://gitlab.com/ru2saig/MatrixUi
