#+BEGIN_COMMENT
.. title: About
.. slug: about
.. date: 2023-07-03 15:13:32 UTC+05:30
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Hello, there! I'm Nidhish, interested in robotics, art, embedded development, free software and anything that beeps and boops. On this website you'll find posts about stuff I find interesting, in-progress projects, experiments and the like. For "finished" projects (for nothing is ever truly done), check this [[https://ru2saig.github.io/projects/][page]]. 

Here is the fingerprint of my public-key:
#+BEGIN_SRC bash
  66DA0E4986996DF91A6FCC6C28ED6EA909E80A8A
#+END_SRC

There could be another uid stating that the key "revokes" another key (0x8267D123856B1271), and that was because I forgot the passphrase for that key. But, miraculously, after a few days of making this key, I remembered what my passphrase was. Then I promptly revoked that old key, because quantum computers.
Anyway, here is my (latest) PGP key:
#+BEGIN_SRC
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBGYtvqkBEACmMbzqS0fdEtsTKZf1F0UjUXYETYIxKakF4Cs7xr5qjiJ1Gas8
tnnELEQgLVghtvyTeOVsaia7ly/ZXyCbeG7Ec4ui+q94wcEKfENKku/IfC/SfTyP
/rEcXsQN0V1gPpKm4VXMb0VckNmkTJds/Opr/TR+VYBtuXmUfMMliVpVojYDWlsJ
JvpKiCBiGqcWppifqA9c0BnIWZKP0ppZ2Rc7cnDEFd3LBBs98GrZKwD7D0Tca6vV
/vBEP2hhlqpAP9Z9yF8xfq3wyFMpfmR4TXc43D16kgi+ZV61byN9qXAQnQXS3qDk
HuAvEfLs4wuHl13A++63Mz5MbbwMD0trk1e8kmVmzzmxIFAPVTARaYLJxi5C6Zvj
4Wt4y1bc2Hmx0lZRZt8j42OebyWvvLOzXQXgYuTj2sbv3vb/vwp6Z/WxVKeSVRzs
AuIr7qeRjLsVnzek0FQVmLIOln6voD2PLZrDkvO/S1l7mwIEjnBHWX2VCkmZau3N
amGJOFEW/KFPJstkqWu9pC+l/5TH1NLj9Q2M6GpS0wN5KqJsyx6v8FDwsDkiSoYV
ud8PeTYfzeHnUq1wqNS84YTOHxfii7FN/zs4rvCqf8+Q+hF550VMgolQMDZ1BGs3
t/k91TZEAHyo2xdvLYhXKgXS5qVRRv0DcduR5P1SfPMrB7++CQd0ogheBQARAQAB
tDBHdXJ1c2FpIE5pZGhpc2ggQ2hhZGl2ZSA8ZGV2ZWxydXVzYWlnQGdtYWlsLmNv
bT6JAlcEEwEIAEEWIQRm2g5Jhplt+RpvzGwo7W6pCegKigUCZi3hswIbAwUJAeEz
gAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRAo7W6pCegKimuFD/4sSSVc
bGn8S7qOgm6VoAibkSVxnOqKseotHSzl7MiqngghtlmQpnSjbaV8lgXkV35+Opkq
FnjsB+qCn3MBStsswb3PTbdNmw76PMR6grYbCrlaV3/MVKG2F6KfzoL9ljDQSsGL
gHf2rX1x7vm01Ffh09d7chhyCI0lvMOz+eoe/LEMz2NbSxWtGgtRUFe10Sw9L4zJ
1aiVb0+5Xs2VNYk1xJs9+kuBbgeCYRhF+ZScOw+fW0v7sVta8gLhgZJYrY3NNtCh
mZtsma6Tevyl7WuFuezNqVDDDMpF0vJbbKXcVyDkN0+VsflrWlaxA55UIRhF2hl2
Ov9j4yYcG+X9wpe3ZV/gx/l64MA/9Dbj+cTcGMDp3/Q32mJudEqqmpxx0b0JREwm
+XZ5A/rwfO6l0ohdCmh7pV1lSH0OSmxXdRltdapZLGqzXXYZwr/wIGMyq9cMmOy5
AY74DyqVQILzgV3xcnfB3NKGoMZ5EifOIf9T0LIgMVONcQ10JMY7z5knSY22hVsN
GE9z39v/CtjuZ7hHKrkzaZn6ziw7MC+W0vo+utqcKEAPaE8XUcxzBslBgqYGRVoH
e5XpKmlPANOzO1pZvo6nZl0fvXUfksN3Jy+ggHDeX3Ydpt7iWgnlbPYIDm47DAG+
9VR/QT8TlcX6e28I7BJnE1F0xGVC9JSpbNE3ebkCDQRmLb6pARAAwjm9aAa8v4RH
Akm6LA1Fgka0d6i9hg0ckiDPzuBjiBlcqYfrXE7IzlM4yuZQ/3OuAXRbAngKNdQU
gWs2nzFe4AqZ2X70syQ5G3KbaGAlcMcr1DBghDhTOMlfQAWOztRS7HeQid+D7J0z
6BmK4WjqvS7jNrCbOR5mveleWuhELqokIMFo2s9eW3OMiFyiLz3QrG5NO9a7pwJ8
o/N8s3TLNDLBh4hTx0mj3hfczSB8QW/4iK6k62Q9EBLFu0ErZvH8rsHzhmxNlgup
ZeeolTNdIcizdkF6afpwSMgmUT8QGqFVgTUuixLYu/nL2pdARL6lDAdp5UnOkS6S
egd1/lhw+rtrP5vyuvDUwP/drfH+TcWn0vE4hd/nqzy/e0EIcXVz2KFAzttQm/gS
K+KDzhXXe9YzwOMRVgL5bVq9lIupoa25bWEg8/RWY+FajN5665413k726Zrxa63s
pU9PBnspznFW9Ccahs+JGfxgp2NBvqKrN71kw8yHUUcrxIgIYOkpIP4USZa4ry3i
HQgPV5PCGDWOlZPgYrlP4rShFdSPA1v7tC7ekdci6LscWQLS8WwcxwYMjipmNJq6
YoLGxnD2P7jvn/pWHyosnoKDvAblvT8QjanVnQCaNz/nljCshppWkhq+UN2Jj6SI
foCzsaofWX/hhL+d9p65YCeleiDIWMEAEQEAAYkCPAQYAQgAJhYhBGbaDkmGmW35
Gm/MbCjtbqkJ6AqKBQJmLb6pAhsMBQkB4TOAAAoJECjtbqkJ6AqKNSwP/1Sf5yyE
nvLuPsgbaNamfBi3UyUTchi1JXv00O/6+F2xAl7xkIEmMJavqRLK0kMggT1D4Nhc
5Hxt5oRgvCumBzf8zWRZfQ1iNZ16vPZNCTQv3zN2MZq5lLEKmbp/WbFBpdnv+ses
YGwmhb1KfTc23iXLNOxIO1jigRdP7wDQS4/DU5Cq54+Ec6/OfrWC+D5a7+6fiPbB
VfxXTrX+24QP139HK0Ooh/jzwVIgi8BaR8cqAV6kPjygiD5LU+K0RkhumieCxkhc
oyzWW+S6UIK6QzlGCPi2uO6RXiySXGLUEc4qFIPT0X7EtdRoo5cDawnOi8LdyilD
31vwGLteMg+XYQnQSkl/HtyvL3Z6F0jz7DFeLrTI1KFRVjxqJro+HWuywwMOPHnl
9i2y23feTyZXl+S2RRVD4vnuilWFpSUlJOhN65TePtUV0t9yJ6SvW5yt+ECn3ePX
6/pxlSNQ5rumBIbAc5RFRBDXB0ydIOZQdet3xKKuBoQLI75kjZ13ymhpZ2xvFk44
3bCOX+cfiS1tWItxA8OhjwQ4MM/ZW5BpB8JeHNZrXPe6QFQB/gaqFZqbOM2Fpk5n
lm+jDEAnZT+vtC7GbsdE4xRQRwkK0DS+HYWzYR+uJuAego7AkoOeY2LhCcNUC/07
SsmrpAYGmTEv66nCLyE0wdQtOspxVvuJbpXR
=DL/8
-----END PGP PUBLIC KEY BLOCK-----
#+END_SRC

Now our secrets shall be safe with us! Or you could verify software I (might) have signed. Or both. Both is good.

Here is where you can find my projects and such:
- https://github.com/ru2saig
- https://gitlab.com/ru2saig
- https://code.swecha.org/ru2saig
